openapi: 3.1.0
info:
  title: file_gen
  version: "1.0.0"
  description: Générer/écrire des fichiers texte (.ini, .inc, .lua, .ps1, .bat, .cmd, .txt).

servers:
  - url: https://rainmeter-actions-server.onrender.com

paths:
  /write:
    post:
      operationId: fileGen
      summary: Écrit un fichier texte et renvoie le chemin/sha256
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              required: [path, content]
              properties:
                path:
                  type: string
                  pattern: '^[\w\-\./\\@# ]+\.(ini|inc|lua|ps1|bat|cmd|txt)$'
                  description: Chemin relatif (côté serveur) sans parcours parent.
                content:
                  type: string
                  minLength: 1
                overwrite:
                  type: boolean
                  default: true
      responses:
        "200":
          description: Fichier écrit
          content:
            application/json:
              schema:
                type: object
                required: [path, bytesWritten]
                properties:
                  path: { type: string }
                  bytesWritten: { type: integer }
                  sha256: { type: string }
