openapi: 3.0.0
info:
  title: run_code
  version: "1.0.0"
  description: Exécuter un extrait court pour tester une idée (Lua, Python, PowerShell, Batch).
paths:
  /run:
    post:
      summary: Exécute un snippet.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              required: [language, code]
              properties:
                language:
                  type: string
                  enum: [lua, python, powershell, batch]
                code:
                  type: string
                  minLength: 1
                stdin:
                  type: string
                timeoutMs:
                  type: integer
                  minimum: 100
                  maximum: 30000
                  default: 5000
      responses:
        "200":
          description: Résultat d'exécution
          content:
            application/json:
              schema:
                type: object
                required: [stdout, stderr, exitCode]
                properties:
                  stdout: { type: string }
                  stderr: { type: string }
                  exitCode: { type: integer }
                  files:
                    type: array
                    items:
                      type: object
                      required: [path]
                      properties:
                        path: { type: string }
                        mime: { type: string }
                        size: { type: integer }