openapi: 3.0.0
info:
  title: search_docs
  version: "1.0.0"
  description: Rechercher dans la doc officielle Rainmeter (manual/forum) pour confirmer une option.
paths:
  /search:
    post:
      summary: Recherche une requête texte.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              required: [query]
              properties:
                query:
                  type: string
                  minLength: 2
                scope:
                  type: string
                  enum: [manual, forum, all]
                  default: manual
                maxResults:
                  type: integer
                  minimum: 1
                  maximum: 10
                  default: 5
      responses:
        "200":
          description: Résultats de recherche
          content:
            application/json:
              schema:
                type: object
                required: [results]
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      required: [title, url]
                      properties:
                        title: { type: string }
                        url: { type: string }
                        snippet: { type: string }